version: '2.1'
services:
  installer:
    build: ./images/installer
    hostname: installer
    container_name: installer
    volumes:
      - ./installer:/installer
      - ./installation:/installation
    environment:
      - COMPOSE_PROJECT_NAME
    healthcheck:
      test: if [ ! -e /installation/installed ]; then (echo "Installation not finished yet" && exit 1) ; fi;
      interval: 1s
      retries: 300
    networks:
      - appmon_net

  appmon_server:
    image: ubuntu
    hostname: appmon_server
    container_name: appmon_server
    volumes:
      - ./installation:$DT_HOME
    depends_on:
      installer:
        condition: service_healthy
    environment:
      - COMPOSE_PROJECT_NAME
    networks:
      - appmon_net
    command: bin/bash -c "(.$DT_HOME/dtfrontendserver &) && .$DT_HOME/dtserver"
    ports:
      # Browser to server ports NonSSL 8020 SSL 8021 (to start the Webstart Client)
      - "${APPMON_WEB_CLIENT_NONSSL_PORT:-8020}:8020"
      - "${APPMON_WEB_CLIENT_SSL_PORT:-8021}:8021"
      # 8040  Non SSL Collector to server port for Web Base Agents (or direct agent to server)
      # 8041  SSL Collector to server port for Web Base Agents (or direct agent to server)
      - "${APPMON_ONEAGENT_NONSSL_SERVER_PORT:-8040}:8040"
      - "${APPMON_ONEAGENT_SSL_SERVER_PORT:-8041}:8041"
      # 2021 Client to Frontend Server - non SSL
      - "${APPMON_CLIENT_NONSSL_PORT:-2021}:2021"
      # 8023 Client to Frontend Server - encrypted via HTTP tunnel
      - "${APPMON_CLIENT_SSL_PORT:-8023}:8023"
      # 9998 - Legacy Agent to server embedded Collector (default)

  appmon_collector:
    image: ubuntu
    hostname: appmon_collector
    container_name: appmon_collector
    volumes:
      - ./installation:$DT_HOME
    depends_on:
      installer:
        condition: service_healthy
    environment:
      - COMPOSE_PROJECT_NAME
    networks:
      - appmon_net
    command: .$DT_HOME/dtcollector
    ports:
      # 9998 - Legacy Agent to Collector
      - "${APPMON_COLLECTOR_PORT:-9998}:9998"
      # 8042 One Agent to Collector non SSL
      - "${APPMON_ONEAGENT_NONSSL_PORT:-8042}:8042"
      # 8043 One Agent to Collector SSL
      - "${APPMON_ONEAGENT_SSL_PORT:-8043}:8043"

networks:
  appmon_net:
    driver: bridge
