dtserver:
  container_name: "${DT_SERVER_NAME}"
  hostname: "docker-${DT_SERVER_NAME}"
  image: dynatrace/server
  environment:
    NAME: "${DT_SERVER_NAME}"
    HOST_NAME: "docker-${DT_SERVER_NAME}"
    LICENSE_KEY_FILE_URL: "${DT_SERVER_LICENSE_KEY_FILE_URL}"
  volumes:
    - "/tmp/log/dynatrace/servers/${DT_SERVER_NAME}:/opt/dynatrace/log/server/${DT_SERVER_NAME}"
  ports:
    - "2021" # Dynatrace Clients (TCP with SSL)
    - "8021" # Dynatrace Web Server (HTTPS)
    - "9911" # Dynatrace Web UI (HTTPS)

dtcollector:
  container_name: "${DT_COLLECTOR_NAME}"
  hostname: "docker-${DT_COLLECTOR_NAME}"
  image: dynatrace/collector
  links:
    - dtserver
  environment:
    NAME: "${DT_COLLECTOR_NAME}"
    HOST_NAME: "docker-${DT_COLLECTOR_NAME}"
  volumes:
    - "/tmp/log/dynatrace/collectors/${DT_COLLECTOR_NAME}:/opt/dynatrace/log/collector/${DT_COLLECTOR_NAME}"

dtwsagent:
  container_name: "${DT_WSAGENT_NAME}"
  hostname: "docker-${DT_WSAGENT_NAME}"
  image: dynatrace/wsagent
  links:
    - dtcollector
  environment:
    NAME: "${DT_WSAGENT_NAME}"
    HOST_NAME: "docker-${DT_WSAGENT_NAME}"
  volumes:
    - /opt/dynatrace
    - "/tmp/log/dynatrace/wsagents/${DT_WSAGENT_NAME}:/opt/dynatrace/log"

dtagent:
  container_name: "${DT_AGENT_NAME}"
  hostname: "docker-${DT_AGENT_NAME}"
  image: dynatrace/agent
  volumes:
    - /opt/dynatrace
    - "/tmp/log/dynatrace/agents/${DT_AGENT_NAME}:/opt/dynatrace/log/agent"