tomcat:
  container_name: tomcat
  image: tomcat
  ports:
  - 8080
  volumes_from:
  - dtagent
  external_links:
  - dtcollector
  environment:
    CATALINA_OPTS: "-agentpath:/dynatrace/agent/lib64/libdtagent.so=name=tomcat-agent,collector=docker-dtcollector"
  command: catalina.sh run