dtserver:
  container_name: "${DT_SERVER_NAME}"
  hostname: "docker-${DT_SERVER_NAME}"
  image: "dynatrace/server:6.2"
  environment:
    NAME: "${DT_SERVER_NAME}"
    HOST_NAME: "docker-${DT_SERVER_NAME}"
    LICENSE_KEY_FILE_URL: "${DT_SERVER_LICENSE_KEY_FILE_URL}"
  volumes:
    - "/tmp/log/dynatrace/servers/${DT_SERVER_NAME}:/dynatrace/log/server/${DT_SERVER_NAME}"
  ports:
    - "2021" # Dynatrace Clients (TCP with SSL)
    - "8021" # Dynatrace Web Server (HTTPS)
    - "9911" # Dynatrace Web UI (HTTPS)