java:
  container_name: java-example
  build: .
  environment:
    JAVA_OPTS: "-agentpath:/dynatrace/agent/lib64/libdtagent.so=name=java-agent,collector=docker-dtcollector"
  volumes_from:
  - dtagent
  external_links:
  - dtcollector
  command: sh -c "java $${JAVA_OPTS} JavaTest"