dtcollector:
  container_name: "${DT_COLLECTOR_NAME}"
  hostname: "docker-${DT_COLLECTOR_NAME}"
  image: "dynatrace/collector:6.2"
  external_links:
    - dtserver
  environment:
    NAME: "${DT_COLLECTOR_NAME}"
    HOST_NAME: "docker-${DT_COLLECTOR_NAME}"
  volumes:
    - "/tmp/log/dynatrace/collectors/${DT_COLLECTOR_NAME}:/dynatrace/log/collector/${DT_COLLECTOR_NAME}"